version: '3.0'
services:
  vader:
    image: docker.pkg.github.com/j718/vim-pandoc-wiki/vader:latest
    container_name: vader
    volumes:
      - .:/vim-pandoc-wiki
    command:
      - /bin/bash
      - -c
      - nvim -Nu /vim-pandoc-wiki/test/.vimrc -c 'Vader! vim-pandoc-wiki/test/main.vader' > /dev/null

